---
- name: Check facts
  hosts: all
  become: yes

#      msg: "{{ ansible_hostname }} has ip address {{ ansible_default_ipv4.address }}"
  tasks:
  - name: Get default IP and Hostname
    debug:
      msg: "{{ ansible_mounts.mount }} has FS type {{ ansible_mounts.fstype }}"
      