---
- name: Manage HTTP service
  hosts: all
  become: true

  tasks:

  - name: install http
    yum:
      name: httpd
      state: latest
  
  - name: restart https
    service:
      name: httpd
      state: started

  
  