---
- name: namage users
  hosts: all
  become: yes

  tasks:

  - name: Create groups
    group:
      name: "{{ item }}"
      state: present
    with_items:
      - group1
      - group2
      - group3
  
  - name: Create user and map 3 group to each
    user:
      name: "{{ item[0] }}"
      state: present
      groups: "{{ item[1] }}"
    with_nested:
      - ['user1','user2','user3']
      - ['group1','group2','group3']