---
- name: Manage VSFTPD and httpd
  hosts: all
  vars:
    packages:
    - httpd
    - vsftpd
  become: yes

  tasks:

  - name: Install all pakcage list
    yum:
      name: "{{ item }}"
      state: latest
    with_items: "{{ packages }}"

  - name: start service
    service:
      name: "{{ item }}"
      state: started
      enabled: true
    with_items: "{{ packages }}"