---
- name: Manage VSFTPD and httpd
  hosts: all
  vars:
    packages:
    - httpd
    - vsftpd
  become: yes

  tasks:

  - name: Install all packages
    yum:
      name: "{{ items }}"
      state: latest
    with_items: "{{ packages }}"

  - name: start service
    service:
      name: "{{ items }}"
      state: started
      enabled: yes
    with_items: "{{ packages }}"